#!/bin/bash
if [ "$(id -u)" != 0 ]
  then echo "Please run installer as root"
  exit
fi

echo "Installing needed packages for SystemDJ"
pacman -Syu > /dev/null 2>&1 && pacman -S git busybox gdc dub gcc > /dev/null 2>&1

echo "Linking needed files to directories"
ln -sf /bin/busybox /sbin/mdev > /dev/null 2>&1
echo "Warning! Now, default init will be changed from your to Busybox Init. Do you want to proceed?"
read answer
if [ $answer == "y" ]; then
  ln -sf /bin/busybox /sbin/init
elif [ $answer == "n" ]; then
  echo "Okay, will link to /usr/bin/init"
  ln -sf /bin/busybox /usr/bin/init
fi

echo "Downloading source of SystemDJ"
git clone https://underlevel.ddns.net/git/underlevel/systemdj > /dev/null 2>&1

echo "Building SystemDJ"
cd $PWD/systemdj && dub build --build=release

echo "Installing SystemDJ"
mv ./systemdjctl /bin/systemdjctl > /dev/null 2>&1
cp /etc/inittab /etc/inittab_old
rm /etc/inittab
echo "::sysinit:/bin/systemdjctl autorun" > /etc/inittab
echo "tty1::respawn:/sbin/getty 38400 tty1" >> /etc/inittab

echo "Installing mdev-like-a-boss"
mkdir -p /opt/mdev
git clone https://github.com/slashbeast/mdev-like-a-boss /opt/mdev
ln -sf /opt/mdev/xorg.conf.d/ /etc/X11/xorg.conf.d/
ln -sf /opt/mdev/mdev.conf /etc/mdev.conf

echo "Writing an basic init scripts"
mkdir -p /etc/init/enabled
mkdir -p /etc/init/disabled

echo "{ \"name\": \"Remount filesystems\", \"executable\": \"mount -o remount,rw /\", \"respawn\": 5 }" >> /etc/init/disabled/remount.json

echo "{ \"name\": \"Mdev Device Manager\", \"executable\": \"/sbin/mdev -s -d\", \"respawn\": 5 }" >> /etc/init/disabled/mdev.json

echo "{ \"name\": \"Hardware Drivers\", \"executable\": \"find /sys -name modalias -type f -print0 2> /dev/null | xargs -0 sort -u | xargs modprobe -b -a 2> /dev/null\", \"respawn\": 5 }" >> /etc/init/disabled/hwdrivers.json

echo "{ \"name\": \"Networking support\", \"executable\": \"/bin/busybox udhcpc -i $(ip link show | awk '/UP / {print $2}' | sed 's/://g')\", \"respawn\": 5 }" >> /etc/init/disabled/networking.json

echo "{ \"name\": \"D-Bus IPC Daemon\", \"executable\": \"/usr/bin/dbus-uuidgen --ensure=/etc/machine-id && dbus-launch\", \"respawn\": 5 }" >> /etc/init/disabled/dbus.json

systemdjctl enable remount
systemdjctl enable hwdrivers
systemdjctl enable mdev
systemdjctl enable networking
systemdjctl enable dbus

chmod +x /etc/init/enabled/autostart.sh

echo "Installation finished. Good luck!"