#!/bin/sh
if [ "id -u" != 0 ]
  then echo "Please run installer as root"
  exit
fi

echo "Installing needed packages for SystemDJ"
pacman -Syyu > /dev/null 2>&1 && pacman -S busybox gdc dub gcc > /dev/null 2>&1

echo "Linking needed files to directories"
ln -sf /bin/busybox /sbin/mdev > /dev/null 2>&1
echo "Warning! Now, default init will be changed from your to Busybox Init. Do you want to proceed?"
read answer
if [ answer == "y" || answer == "yes" ]
  ln -sf /bin/busybox /sbin/init
fi

echo "Downloading source of SystemDJ"
git clone https://underlevel.ddns.net/git/underlevel/systemdj > /dev/null 2>&1

echo "Building SystemDJ"
cd $PWD/systemdj && dub build --build=release

echo "Installing SystemDJ"
mv ./systemdjctl /bin/systemdjctl > /dev/null 2>&1
echo "::sysinit:/bin/systemdjctl autostart \n tty1::respawn:/sbin/getty 38400 tty1 \n tty2::respawn:/sbin/getty 38400 tty2" >> /etc/inittab > /dev/null 2>&1

echo "Installing mdev-like-a-boss"
mkdir -p /opt/mdev
git clone https://github.com/slashbeast/mdev-like-a-boss /opt/mdev
ln -sf /opt/xorg.conf.d/ /etc/X11/xorg.conf.d/
ln -sf /opt/mdev.conf /etc/mdev.conf

echo "Now, you will need to write your own init files."
echo "Example: \
{ \
	"name": "mdev Device Manager", \
	"executable": "/sbin/mdev -d -s", \
	"respawn": 5 \
}"

echo "Installation finished. Good luck!"

